#+TITLE:     PDF Tools Mod README
#+AUTHOR:    Tongjie Chen
#+EMAIL:     chenphy10@gmail.com

This is modified from [[https://github.com/politza/pdf-tools][pdf-tools]] and drawing inspiration from [[https://github.com/weirdNox/org-noter][org-noter]].

Original readme files can be referred to them. I am not familiar with building programs so I did not make a build of this.

The files here are my package folder.

** Fix annotation place mismatch
   From poppler 0.86, the highlighted region will be different than actual highlighted area shown in PDF files.

   On Woindows, I used poppler 0.85 in Mingw to compile epdfinfo and attach related files here.

   In Linux I compiled epdfinfo with 0.84 and put those lib.so files to a directory and used "export LD_LIBRARY_PATH=" to load them before executing Emacs or Emacsclient.

   Don't load these lib together with programs like Evince or they will break.

** Show highlighted text in pdf-annot-list
   The changes are in pdf-annot.el. Adding a function to extract the highlighted text including thanks to "org-noter--pdf-tools-edges-to-region" borrowed from org-noter. Also word break at end of PDF lines removed to increase legibility.
   
** Annotation editor in orgmode
   I modded the mode to make it use orgmode to edit, thus hyperlinks can be used.

   But showing annotation is still in fundamental mode that I need to fix.

** pdf-occur default to occur selected text
   If you don't input any text in pdf-occur but selected a region of text, it will occur those text. But work needed to be done to show in the prompt.

** TODO Thumbnails with Evince
   I tried to modify pdf-view-goto-page to make it show file simutaneously in Evince, but Evince will always pop up to grab window focus.

** TODO Click to open a new window for reference
   Internal links in PDF should be clicked and open a new window to show the referred place for better reference.

# Local Variables:
# mode: org
# End:
